name: buscatelo
description: Hotel finding. An awesome Flutter challenge.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: any
  provider: any
  bordered_text: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  pedantic: ^1.8.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/img/logo.png"
  image_path_android: "assets/img/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo.png
    - assets/img/fav_icon.png
